### ISSUE TITLE
[Bug] Anti Hunger makes you not able to swim through a 1 block hole (in water)

### ISSUE THREAD

**Issue by doggiedogdog323** [MeteorDevelopment/meteor-client#1310]
**Describe the bug**
Anti Hunger makes you not able to swim through a 1 block hole (in water)
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context (meteor version, minecraft version, other mods you are using, etc).

**Comment by Walaryne** [comment]
Because the server is never told that the client is sprinting, due to the way that Anti Hunger works, the server does not know you're swimming because the packet for sprinting (which is the same) is never sent. So unfortunately this cannot be fixed as it would undermine the functionality of Anti Hunger. @MineGame159 you may wanna close this unless you can think of something else.

**Comment by RedCarlos26** [comment]
It could be fixed by having a in water check, which disables anti hunger in a way only when you are in water (like the sprinting is sent even if it's on when you are in water)
