### ISSUE TITLE
new chunks

### ISSUE THREAD

**Issue by RafWasTaken** [MeteorDevelopment/meteor-client#1367]
**Describe the feature**
a thing that lets you see if a chunk has been loaded or not

**Screenshots**
none

**Additional info**
none

**Comment by mrphi06** [comment]
Is it possible to do this using inhabited time? Like if inhabited time is 0 then show it. I do not know much about it, but I think it is a variable per chunk. It could also help because you could do a heatmap or add a slider for the min and max inhabited time so that you could see if somebody has a base nearby if the inhabited time suddenly goes up? I think this would be a better system than the if water is flowing one.

**Comment by C10udburst** [comment]
wtf is inhabited time? i dont think that exist in [what is being sent to client](https://wiki.vg/Chunk_Format#Packet_structure). Using water is possibile (there already exists an addon for that)

**Comment by mrphi06** [comment]
It is probably a server side thing then. I thought it would also be sent to the client, but I guess not. Inhabited time along with the phase of the moon is used to calculate local difficulty and other things like that.
