### ISSUE TITLE
[Suggestion] Please Add teleport hack

### ISSUE THREAD

**Issue by RouZong** [MeteorDevelopment/meteor-client#1538]
### Describe the feature

In other hack client like:
[Video](https://streamable.com/ops3nq)

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by RickyTheRacc** [comment]
Retard

**Comment by RouZong** [comment]
> Retard

What mean?

**Comment by bryiewes** [comment]
Problem 1. You didn't show if the account has op.
Problem 2. Anticheat would fuck you over
Problem 3. WHY

**Comment by RouZong** [comment]
> Problem 1. You didn't show if the account has op.
> Problem 2. Anticheat would fuck you over
> Problem 3. WHY
1.
It's not need op permission.
2.
It's can skip anticheat.
3.
It's very useful.

**Comment by StormyBytes** [comment]
To be able to teleport like the `/tp` command, you would need an exploit as even a simple anticheat would be able to detect you teleporting. Its just a matter of sudden drastic change in coordinates.

Even then if you somehow found an exploit to do so, you would most likely only be able to use it on a handful of servers or a specific server type because different servers may have different anticheats. 

Considering meteor has about 10k+ users, there certainly would be players who dont play on servers with the exact same anticheat. It is considered bad practice to implement a feature which only works for a few users and dont work for the rest.

**Comment by RouZong** [comment]
> 為了能夠像`/tp`命令一樣傳送，您需要利用漏洞，因為即使是簡單的反作弊也能夠檢測到您正在傳送。這只是坐標突然劇烈變化的問題。
> 
> 即便如此，如果您以某種方式發現了一個漏洞利用，您很可能只能在少數服務器上使用它，因為不同的服務器可能有不同的反作弊。
> 
> 考慮到meteor 有大約10k 用戶，肯定會有一些玩家不在具有完全相同反作弊的服務器上玩遊戲，並且實施僅適用於少數用戶而不適用於其餘用戶的功能被認為是不好的做法。

It's not like /tp command,Did you watch the video?

**Comment by bryiewes** [comment]
It dosent matter. The vanilla anticheat will kick you back with it. It won't work well. No point in adding it. Code it yourself

Sent via the Samsung Galaxy A12, an AT&T smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by balamutac** [comment]
.hclip and .vclip

**Comment by Justgamer101** [comment]
lmao

**Comment by master7720** [comment]
dumbass xD

**Comment by RouZong** [comment]
> 笨蛋xD
you also

**Comment by RouZong** [comment]
> .hclip and .vclip

thanks
