### ISSUE TITLE
[Suggestion] Remove .panic

### ISSUE THREAD

**Issue by RickyTheRacc** [MeteorDevelopment/meteor-client#1894]
### Describe the feature

Replace it with an "all" parameter in the .toggle command so cheaters don't immediately find it

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
It doesnt exist.

**Comment by SIMULATAN** [comment]
https://github.com/MeteorDevelopment/meteor-client/blob/master/src/main/java/meteordevelopment/meteorclient/systems/commands/commands/PanicCommand.java yes

**Comment by RickyTheRacc** [comment]
I updated the comment mimgam monke

**Comment by SIMULATAN** [comment]
> I updated the comment mimgam monke

very good and valid reason actually

**Comment by RickyTheRacc** [comment]
Spam

**Comment by RedCarlos26** [comment]
True

**Comment by tomasventura13** [comment]
what? why

**Comment by SIMULATAN** [comment]
> what? why

cause it's only useful for servers where meteor isn't allowed on which isn't supported by meteor

**Comment by arlomcwalter** [comment]
> > what? why
> 
> 
> 
> cause it's only useful for servers where meteor isn't allowed on which isn't supported by meteor

no, because it shouldn't be called panic, it is now just .toggle all <on/off>

**Comment by DataM0del** [comment]
No smart person cares because "the cheaters", the client barely even bypasses anything, and if it does, that thing is a effectively a meme. Also, if you were looking for this, I suggest you use LiquidBounce Nextgen (or Legacy, but izuna will kill me if I dare recommend Legacy, and it's actually discontinued this time since PRs won't be accepted). You may say, "but you're a cheater, so your opinion doesn't matter." Everyone here is a "cheater", this "utility" client can be used on servers, even if they have an anticheat, you could also use addons. So, are you going to remove addons, just because "the cheaters"? No.
I just don't understand how these stupid legits manage to make my IQ go down by 15 every time, and just because mainly "cheaters" use this, magically something like a security issue, the responses go from "Who let this happen?", "How did this happen?", "How horrible is this platform's security?", turns into "The cheaters got their karma", "L cheaters", "It's their time to take the L".
Legit players are just... 🤦
