### ISSUE TITLE
starting the game doesn´t work

### ISSUE THREAD

**Issue by MJMALTE32** [MeteorDevelopment/meteor-client#1954]
### Describe the bug

When I start fabric it just crashes and I don´t know why it yust says it crashed and nothing eles

### Steps to reproduce

```bash
starting my game
```

### Meteor Version

0.4.6

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by MineGame159** [comment]
Send crash report

**Comment by dylif** [comment]
Is 0.4.6 even supposed to work on 1.18?

**Comment by MineGame159** [comment]
Yeah that's it, it's not

**Comment by Topmotiviert** [comment]
i have that same bug but for 1.18.1 and my crash report says:
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1922.method_8321(net.minecraft.class_2338)" because "$$1" is null
Exit-Code: -1
if anyone can help us witch that information

**Comment by arlomcwalter** [comment]
'that same bug'
