### ISSUE TITLE
[Suggestion] Forge Support.

### ISSUE THREAD

**Issue by MistressPlague** [MeteorDevelopment/meteor-client#1986]
### Describe the feature

Addition of forge support alongside fabric would be extremely nice for compatibility.

### Before submitting a suggestion

- [x] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Justgamer101** [comment]
how about let's all rewrite this entire client so it can work for forge.

**Comment by MistressPlague** [comment]
Entire would not need rewritten.
Furthermore, entertaining to read the aggravational mindset to a reasonable suggestion.

**Comment by Theboiboi8** [comment]
> Entire would not need rewritten. Furthermore, entertaining to read the aggravational mindset to a reasonable suggestion.

due to the client being made solely for fabric, and therefore using a crap-ton of fabric specific features and classes, to make it compatible with forge one would need to rewrite hundreds of files, rename countless folders and it would just make things very complicated. Not to mention that there are no benefits to using forge over fabric in this scenario and switching would make people lose mods that they may rely on. Meteor is also incompatible with optifine, even through optifabric and the forge version would be very unstable if not borderline unusable with optifine, which is the only sensible alternative to iris, sodium, phosphor, lithium, continuity, etc.

**Comment by MistressPlague** [comment]
I use other mods with forge; hence the compatibility mention. It was not referring to optifine.
