### ISSUE TITLE
[Suggestion] Improve Infinity miner so it can chop wood and sand properly

### ISSUE THREAD

**Issue by Tobbeishere** [MeteorDevelopment/meteor-client#2101]
### Describe the feature

Make so Infinity miner doesnt ask for a mending **pickaxe** when you set it to mine wood & sand   makes no sense and it ignores autotool too when infy miner is on

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by MineGame159** [comment]
Use Baritone, eg `#mine oak_log`

**Comment by Tobbeishere** [comment]
that's lazy asf rofl   so cause the cheat doesnt work properly you'll go and use baritone instead?

**Comment by MineGame159** [comment]
????????? The whole point of Infinity Miner is that you are able to mine longer because when the durability of your pickaxe reaches some threshold it will go mine some other block to gather xp and repair the pickaxe with mending. How do you want to do that with sand or logs? Also just so you know, Infinity Miner is just using Baritone.

**Comment by Justgamer101** [comment]
lol
