### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by HerobrineMag** [MeteorDevelopment/meteor-client#2218]
### Describe the bug

please fix the profiles system, before restarting the game I save some settings, when I load this profile later, I have other settings

### Steps to reproduce

```bash
I launch and then change for myself
```

### Meteor Version

0.4.8

### Minecraft Version

1.18.2

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Theboiboi8** [comment]
Profiles only have the settings that are saved on them, and will load the saved settings. If you want to save new settings to a profile, you need to save it again after modifying your settings. Profiles having different settings when you load them compared to last played is not necessarily an issue, in fact it's the expected behavior for profiles with one set of settings, and different settings that are not saved for the actual client when playing. Also, please fix your grammar.

**Comment by SIMULATAN** [comment]
I'd like to see a profile system like in many other clients implemented where you're just using one profile that gets saved and loaded to automatically instead of the "click to copy values" approach

**Comment by arlomcwalter** [comment]
> I'd like to see a profile system like in many other clients implemented where you're just using one profile that gets saved and loaded to automatically instead of the "click to copy values" approach

shut up

**Comment by Theboiboi8** [comment]
Based
