### ISSUE TITLE
What is the reason for Timer???

### ISSUE THREAD

**Issue by maxyra2020** [MeteorDevelopment/meteor-client#2297]
### Describe the feature

What is the reason for timer, I just want to know sorry for bothering you.

### Before submitting a suggestion

- [x] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

**Comment by Lovecrafts-Cat** [comment]
If you bothered to read the code for the [Timer](https://github.com/MeteorDevelopment/meteor-client/blob/3e947d9eeb8f6443035debd7766ceb4e6ccfd7c7/src/main/java/meteordevelopment/meteorclient/systems/modules/world/Timer.java) module,
you'd know that it modifies a multipler for Tick Speed, which is applied globally because of how Minecraft works.

Thus, this module is unable to change the multiplier on specific entities only.

**Comment by maxyra2020** [comment]
> If you bothered to read the code for the [Timer](https://github.com/MeteorDevelopment/meteor-client/blob/3e947d9eeb8f6443035debd7766ceb4e6ccfd7c7/src/main/java/meteordevelopment/meteorclient/systems/modules/world/Timer.java) module, you'd know that it modifies a multipler for Tick Speed, which is applied globally because of how Minecraft works.
> 
> Thus, this module is unable to change the multiplier on specific entities only.
Ohhhhh

**Comment by arlomcwalter** [comment]
> If you bothered to read the code for the [Timer](https://github.com/MeteorDevelopment/meteor-client/blob/3e947d9eeb8f6443035debd7766ceb4e6ccfd7c7/src/main/java/meteordevelopment/meteorclient/systems/modules/world/Timer.java) module,
> 
> you'd know that it modifies a multipler for Tick Speed, which is applied globally because of how Minecraft works.
> 
> 
> 
> Thus, this module is unable to change the multiplier on specific entities only.

it *technically* could but only in singleplayer
