### ISSUE TITLE
Can't download meteor client 1.19 [Bug] 

### ISSUE THREAD

**Issue by theprisoner55** [MeteorDevelopment/meteor-client#2601]
### Describe the bug

Basically, when I got on the website, I opted for 1.19, so I clicked on the 1.19 button, and it didn't work. "Error 523; Origin is unreachable." However, I can download 1.19.1 which is weird.

### Steps to reproduce

```bash
1. go onto meteorclient.com 

2. Click Release 0.5.0 [1.19]
```

### Meteor Version

1.19

### Minecraft Version

1.19

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by RacoonDog** [comment]
maven is down, cope

**Comment by quickz12** [comment]
same

**Comment by quickz12** [comment]
it happens for me aswell

**Comment by anonyco** [comment]
For anyone else dealing with this problem, here's version 0.5.0 of Meteor for Minecraft 1.19.0 (happened to have it in my mods folder). 

Note that the `.zip` file extension must be changed to `.jar` after download in order to work.

[meteor-client-0.5.0-1566.zip](https://github.com/MeteorDevelopment/meteor-client/files/9277463/meteor-client-0.5.0-1566.zip)

**Comment by RacoonDog** [comment]
> [meteor-client-0.5.0-1566.zip](https://github.com/MeteorDevelopment/meteor-client/files/9277463/meteor-client-0.5.0-1566.zip)
 sus link

anyways
https://meteorclient.com/download?devBuild=1571 for 1.19.1
https://meteorclient.com/download?devBuild=1569 for 1.19

^ use these as they are the latest for both versions

**Comment by MineGame159** [comment]
Fixed.
