### ISSUE TITLE
An expandable minimap with biome and structure finder

### ISSUE THREAD

**Issue by Zula-Corvus-Adler** [MeteorDevelopment/meteor-client#2835]
### Describe the feature

An adon similar to journeymap along with a biome finder and possibly a structure finder to find things such as ancient cities or woodland mansions would be great. It would be a very useful tool not only to find structures but to find exotic animals as well.
I also have a second suggestion of a godmode button that gives you insane resistance and regeneration and possibly instant health every second or so instead of having to do it manually in the potion spoof option as a quality of life/ease of use improvement.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Maxo6453** [comment]
1: Instead of requesting journeymap be a part of meteor, why wouldn't you just use journeymap alongside meteor?
2: To find biomes and structures, just use a [seedcracker](https://github.com/19MisterX98/SeedcrackerX/releases/tag/2.13).
3: A "godmode" button is a cool idea, but I think the devs would rather work on something more important. (correct me if I'm wrong)
