### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by ae23rn7diu2** [MeteorDevelopment/meteor-client#3618]
### Describe the feature

Where can you see all versions of meteor client?

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
This is literally a GitHub repository, so you can look at all commits, and find any version since the first public release.
Although, you must build whatever version you want from source.

TL;DR: we do not directly provide downloads to older versions, and suggest you use [ViaFabricPlus](https://modrinth.com/mod/viafabricplus) with the [latest version of Meteor](https://meteorclient.com/download?devBuild=latest), which will let you join older servers.

**Comment by ManInMyVan** [comment]
[https://maven.meteordev.org](https://maven.meteordev.org)
