### ISSUE TITLE
Crash bc of Inventory Tweaks

### ISSUE THREAD

**Issue by Ompyl** [MeteorDevelopment/meteor-client#3770]
### Describe the bug

When using the latest version of Meteorclient and enabling Inventory Tweaks, if the offhand key is pressed when hovering over an armor slot in the inventory the Game crashes. (I Think bc of xCarry)

### Steps to reproduce

```bash
1. Enable Inventory Tweaks
2. Enable xCarry in Inventory Tweaks
3. Open Inventory and click the offhand key (default: f) while hovering over an armor slot.
```

### Meteor Version

Newest

### Minecraft Version

Newest

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
attach a crash report

**Comment by Ompyl** [comment]
https://pastebin.com/raw/UKwyeUwj

**Comment by Wikinger8** [comment]
I think it is because of ArmorStorage not xCarry and an easy fix I found is to change Line: 79 to `clickSlot(syncId,` 45, armorSlot, SlotActionType.SWAP, player); //invert swap` at src\main\java\meteordevelopment\meteorclient\mixin\ClientPlayerInteractionManagerMixin.java

Works perfectly in creative mode but in survival mode you cant use the hotkeys anymore to get blocks into your armor slots or out of them
