### ISSUE TITLE
Reproducable builds

### ISSUE THREAD

**Issue by fw4hre0xxq** [MeteorDevelopment/meteor-client#3903]
### Describe the feature

I'd like reproducible/signed builds. When it comes to anarchy, it makes sense to be cautious about this stuff. I think it would be nice to have builds that use GitHub's auto build tools/some kind of CI/build automation, that kind of thing so that builds can be signed and reproducible.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RacoonDog** [comment]
> ### Describe the feature
> I'd like reproducible/signed builds. When it comes to anarchy, it makes sense to be cautious about this stuff. I think it would be nice to have builds that use GitHub's auto build tools/some kind of CI/build automation, that kind of thing so that builds can be signed and reproducible.
> 
> ### Before submitting a suggestion
> * [x]  This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)
> * [x]  This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

Meteor's builds are already automated

**Comment by MineGame159** [comment]
As was already said, we already use GitHub actions to build every commit and upload it to the maven which is then linked on the website as the download button. They are already reproducible as you have full access to the source code and signing is not really a thing people do with jar files. Also kinda pointless since if you dont trust it then you can just build it yourself.
