### ISSUE TITLE
.peek doesnt show some blocks

### ISSUE THREAD

**Issue by SusgUY446** [MeteorDevelopment/meteor-client#4087]
### Describe the bug

link to a video: https://discord.com/channels/689197705683140636/1153216364291567656/1153216364291567656

### Steps to reproduce

```bash
take a shulker box (whit stone bricks as an example.) (on a the server 5b5t) and then use .peek.
```

### Meteor Version

0.5.4

### Minecraft Version

1.20.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

**Comment by Wide-Cat** [comment]
This is probably an issue specific to 5b5t due to the strange way they translate shulker box data. We would almost certainly have to do a lot of work to fix it; unless this happens on other servers as well it wouldn't be worth the effort. If this does happen on other servers feel free to reopen the issue, but even so it would probably be unlikely to be fixed.
