### ISSUE TITLE
[Suggestion]  Quilt support

### ISSUE THREAD

**Issue by LaneurXD** [MeteorDevelopment/meteor-client#4221]
### Describe the feature

Could pls add support to quild

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
Meteor has always been shared as a Fabric mod.
Just because it is a fork of Fabric, it does not mean all Fabric mods will run on it.
If it used to work on Quilt before, it was by chance, and not intentional.
Testing the latest dev build, it no longer seeems compatible.

We're not interested in supporting another mod loader, when that brings virtually no advantages in the dev space or to the end user.
