### ISSUE TITLE
FUTURE CLIENT

### ISSUE THREAD

**Issue by somsoma12** [MeteorDevelopment/meteor-client#4303]
### Describe the feature

MAKE IT SO ITS COMPATIBLE WITH FUTURE PLSSS IM BEGGING 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by RealmKebab** [comment]
but why use 2 clients at once?

**Comment by somsoma12** [comment]
> but why use 2 clients at once? + meteor is compatible with future, it now crashes (which is a bug) #4141

its not compatible

and i wanna use 2 client bc future doesnt have alot of modules that meteor can easily have with pulgins

**Comment by RealmKebab** [comment]
> its not compatible

it WAS compatible, but not anymore

> and i wanna use 2 client bc future doesnt have alot of modules that meteor can easily have with plugins

you're better off using meteor, future's native version is 1.12.2

**Comment by epicfacethe3rd** [comment]
> you're better off using meteor, future's native version is 1.12.2
Future has been rewritten for modern versions for about a year now. so I'm not sure exactly what you mean by "native version"
And no, you're not better off just using meteor. On anarchy servers with stricter anticheat, meteor desyncs like crazy to where it's beyond useless for pvp. most notably on constantiam. and from the conversations I've had on discord, i don't think this will change any time soon.
so yeah, there is a very good reason to run meteor and future at the same time.

**Comment by DoritoBob777** [comment]
so i managed to get it to work. it was not a problem with rusher. future and meteor are only compatible on one 1.20.1 version. "meteor-client-0.5.4-1935.jar" due to the fact that meteor doesn't store its older versions, which is a bit stupid as there are very little downsides of it, it is hard to get your hands on this version. one way is to rewrite the code so it works with future i personally dont know how to do this but if your smart this is probably the best way. or. you can download it from someone else who has it. i would never recommend downloading anything form anyone ever however i needed meteor so i took the risk and asked someone i trust who had the file. long story short thats the only version that works with future on 1.20.1 and i can confirm it works. if you want the .jar file dm me on discord "doritobob777" and ill send it to you. if you dont trust me however you will have to find someone else, or, rewrite the clients code.
