### ISSUE TITLE
meteor crashes when future is in my mods folder

### ISSUE THREAD

**Issue by DoritoBob777** [MeteorDevelopment/meteor-client#4353]
### Steps to reproduce

so i recently got future but when i put the 1.20.1-20.3 future loader in my mods folder with rusher, meteor and boze, it crashes. 
it works fine with rusher and boze but when paired with meteor it spazzes out.
i havent reproduced this on the latest dev build as future is not compatible with it.
also, ik there are other reports of this crash happening but noone seems to have fixed it so pls help
thanks
DoritoBob777

### Link to crash report/log (upload to https://mclo.gs and paste resulting link here)

https://mclo.gs/EFQWiRG

### Meteor Version

0.5.4

### Minecraft Version

1.20.1

### Operating System

macOS

### Before submitting a crash report

- [ ] This crash wasn't already reported (I have searched crash reports on GitHub).

- [ ] This is a valid crash (I am able to reproduce this on the latest dev build).

**Comment by Theboiboi8** [comment]
Why would you need 4 clients at the same time though? That seems very counterintuitive, and compatibility issues are almost guaranteed to arise, what with 4 different clients all trying to do the same things. I would advise stocking to only 1 client, 2 at most, as any more is just utterly useless in most (all) cases, and just causes unnecessary pain when troubleshooting and unnecessary strain on your computer. The benefits of using 4 clients are far outweighed by the benefits of not, and crashes are definitely one of the guaranteed cons.

**Comment by epicfacethe3rd** [comment]
@Theboiboi8 the reason is that meteor causes a lot of desync and generally does not work on anarchy servers with stricter AC
to copy my explaination from a prior comment
              > you're better off using meteor, future's native version is 1.12.2

Future has been rewritten for modern versions for about a year now. so I'm not sure exactly what you mean by "native version"
And no, you're not better off just using meteor. On anarchy servers with stricter anticheat, meteor desyncs like crazy to where it's beyond useless for pvp. most notably on constantiam. and from the conversations I've had on discord, i don't think this will change any time soon.
so yeah, there is a very good reason to run meteor and future at the same time.

_Originally posted by @epicfacethe3rd in https://github.com/MeteorDevelopment/meteor-client/issues/4303#issuecomment-1880207251_

**Comment by epicfacethe3rd** [comment]
also, its worth noting that this crash is probably caused in part by rh being in your mods folder. that said, i get the same issue

**Comment by DoritoBob777** [comment]
@epicfacethe3rd so i managed to get it to work. it was not a problem with rusher. future and meteor are only compatible on one 1.20.1 version. "meteor-client-0.5.4-1935.jar" due to the fact that meteor doesn't store its older versions, which is a bit stupid as there are very little downsides of it, it is hard to get your hands on this version. one way is to rewrite the code so it works with future i personally dont know how to do this but if your smart this is probably the best way. or. you can download it from someone else who has it. i would never recommend downloading anything form anyone ever however i needed meteor so i took the risk and asked someone i trust who had the file. long story short thats the only version that works with future on 1.20.1 and i can confirm it works. if you want the .jar file dm me on discord "doritobob777"  and ill send it to you. if you dont trust me however you will have to find someone else, or, rewrite the clients code.
