### ISSUE TITLE
When does Meteor stopped supporting cracked launchers?

### ISSUE THREAD

**Issue by FelicityRUX** [MeteorDevelopment/meteor-client#4385]
### Describe the feature

I decided to use Meteor, but it just crashed! I used cracked launcher, and you might think: "You just used cracked laucher, so what's why it crashed", but guess what: before that, it didn't crash! So, does that mean, before that it didn't had that protection?

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by dauser-dev** [comment]
Are you retarded?

**Comment by Big-Iron-Cheems** [comment]
If you look at the crash logs posted by cracked users, you'll notice the same error in all of them: a mixin failure in the Minecraft authentication library.

This is happens because cracked launchers modify the Minecraft JAR in a way that usually bypasses the auth step (not to mention, they use an older version of Authlib). 
This breaks compatibility with some of our mixins in the same library, for example the alt manager ones, crashing the game.

So, we didn't really intentionally make Meteor incompatibile with cracked launchers, it's just a fortunate coincidence for us that cracked launchers made themselves incompatible. 

As we said many times in the website FAQ and in our Discord server that we do not support cracked launchers, and won't provide any support with them, as the users don't own the game legitimately.

**Comment by quangei** [comment]
have any ways to use meteor with cracked launcher in the future ?

**Comment by quangei** [comment]
i find the crack launcher that can be run new meteor client
https://github.com/UltimMC/Launcher
