### ISSUE TITLE
Proxy Channel

### ISSUE THREAD

**Issue by Aexure** [MeteorDevelopment/meteor-client#4563]
### Describe the feature

Create a new channel for users to share proxy configs.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by Big-Iron-Cheems** [comment]
> share proxy configs

So... you intend people to share around IP:port pairs?
Because, there's not really anything else to "config".

There's plenty of free proxies [online](https://github.com/TheSpeedX/PROXY-List).
As always, free proxies are not necessarily always active, which is why if you really need one, then you should buy one from a dedicated, trusted service.
