### ISSUE TITLE
[SUGGESTION] good client but

### ISSUE THREAD

**Issue by 453452hw** [MeteorDevelopment/meteor-client#653]
instead of making a bunch of issues this what im doing.

meteor client good client but i have some issues with it

scaffold fastt tower is a mess

crystal aura is not very poggers

i would like a grid snap or something to move around the module lists so i dont have to spen 5 minutes aligning them for my autism

its so easy to lose waypoints. they dont seem to load on launch like in configured them to. 

people are breaking my surround tnat have higher ping than me how. 

pls add a gamama slider to fullbright and give a somooth transiotion from default to fullbright and reverse

anyways great cliemt keep improving keep doing what ur doing and snale is hot

**Comment by seasnail8169** [comment]
Please make separate issues for each issue. Some of these are bugs and some are suggestions and its annoying having issues like this because when I go through them i just look by title and this is meaningless. Also when i fix/deal with one of these issues i have to leave the issue open until all of the points are resolved.

**Comment by 453452hw** [comment]
sowwy snale
