### ISSUE TITLE
[Suggestion] Message encryption

### ISSUE THREAD

**Issue by StormyBytes** [MeteorDevelopment/meteor-client#683]
**Description**
I was reading the discord server the other day and saw the idea of encrypting messages in chat and only meteor users could decrypt it.
However instead of using base64 or Caesar cipher (which can be easily decrypted by people who have an iq of atleast 20) we use a vigenere cipher instead.

- Since a vignere cipher requires a key to be decrypted, it is more secure.
- The key is also obtained from the API, the same way meteor users obtain information about other meteor users from the API. And therefor only meteor users can access them.
- The key will be updated each day (or in some other time period) and it will be a string of 4 to 8 characters. 
- There will also be a prefix when you encrypt a message. The reason for this prefix is so that other meteor users know that this specific message is encrypted and not just random gibberish. This prefix could be encrypted as well.

**Comment by HENRYMARTIN5** [comment]
noice

**Comment by CountBleck** [comment]
The whole idea sounds insecure. Why not use AES on the message and send the Base64ed result?
I don't see a use for an encrypted prefix since Meteor would have to try and decrypt every message and see if there is a prefix, which would be a waste of time. There's no real advantage to an encrypted prefix.
Also, anyone can access an API, unless authentication is required. What would you authenticate with?
And what's the use of encrypting a message for all Meteor users to see anyways?

**Comment by StormyBytes** [comment]
Now that I think of it, yeah you're right. It's pointless and also insecure.

**Comment by CountBleck** [comment]
Also, I think people could take advantage of this to slow people's computers down a tiny bit by spamming the chat with a bunch of encrypted messages that Meteor would have to waste time decrypting for no reason at all.
Isn't there also a limit to the number of characters in chat messages?
Just use Discord, Guilded, etc., or, if you're extra paranoid, Matrix.
