### ISSUE TITLE
[Bug] Elytra fly making elytra's disappear

### ISSUE THREAD

**Issue by tinmarr** [MeteorDevelopment/meteor-client#696]
**Describe the bug**
Sometimes when I have elytra fly on (chest swap set to wait for ground) my elytra just disappears and I can't get it back.
Not sure how or why this is happening but it might happen if I open my inventory quickly after landing.

**Additional context**
Meteor Version 0.4.3 836

**Comment by RoastedCheese** [comment]
This most likely happens because you change dimension while your elytra is "glitched". I'm pretty sure it's related to chest swap and not efly. If you open your inventory while you have this bug the elytra will be in your mouse and if you change dimension while doing so it drops on the ground, similar to what happens when an item is in a crafting slot.

**Comment by The-Warlord** [comment]
I think it's a problem with autoarmor and chestswap. I made my autoarmor toggle off when I use chestswap and I've had no issues.

**Comment by tinmarr** [comment]
Thank you @The-Warlord. That fixed it!
