### ISSUE TITLE
[Bug] Canvas not working fine

### ISSUE THREAD

**Issue by DrDuggi** [MeteorDevelopment/meteor-client#965]
**Describe the bug**
Shader mod, just make shader like

**To Reproduce**
1. Go to Forge and download canvas
2. Go on 'Play On minecraft'
3. Then activate ESP

**Expected behavior**
It should not render like this

**Screenshots**
![image](https://user-images.githubusercontent.com/62102560/120940042-6952a380-c71b-11eb-9a01-adbcda07d01b.png)

**Additional context**
MC 1.16 METEOR 0.4.4 "Info my 2 error"

**Comment by NobleOMD** [comment]
I'm fairly sure that this is to do with sodium and canvas not working together see:
![image](https://user-images.githubusercontent.com/25640076/121073952-1b957400-c7cb-11eb-8c19-4dac0217ebfe.png)

Meteor uses sodium as its renderer and so that is the problem here. It is a known issue between sodium and canvas and can't ever be fixed becuase of the reasons stated above.

**Comment by MineGame159** [comment]
Fixed
